### PR TITLE
Include slides from reimer:2020

### PR DESCRIPTION
**Pull request by janheinrichmerker**
Add the slides for my thesis "Bias in Learning to Rank Caused by Redundant Web Documents".
To be merged only _after_ https://github.com/webis-de/downloads/pull/1 is merged.

### CODE REVIEW

**Comment by janheinrichmerker** [comment]
@mam10eks As you've merged https://github.com/webis-de/downloads/pull/1, could you please also merge this PR? Thanks!

**Comment by mam10eks** [comment]
Ah, @heinrichreimer I did not see this pull request here, thanks for the reminder.

In fact we do not manually edit this page, since it is produced from our bib-files.
I have updated the page accordingly: https://webis.de/for-students/completed-theses.html#reimer_2020

**Comment by janheinrichmerker** [comment]
Good to know @mam10eks! So what's the appropriate way to update bibliographies?

**Comment by mam10eks** [comment]
We have the bibliographies in our CVS, but only PhD students, Postdocs, and Profs have access to the CVS, so I updated this and generated the page again.

**Comment by janheinrichmerker** [comment]
Ah I see. Thanks again for updating!

**Comment by mam10eks** [comment]
Youre welcome! :)

**Pull request closed without merging**
