### PR TITLE
Add Label Studio service

### PR DESCRIPTION
**Pull request by janheinrichmerker**
_Preview:_
Screenshot from 2021-06-26 00-54-25

### CODE REVIEW

**Comment by potthast** [comment]
Should we create a single categor "Labeling tools" (or similar) and list all the ones deployed, rather than creating an entry for each one?

**Comment by potthast** [comment]
@johanneskiesel What do you think? Should we combine the two entries into one? We have done this similarly for cluster computing frameworks.

**Comment by johanneskiesel** [comment]
ah yeah, sorry... I thought the message box I saw was for writing a comment, but it instead became the commit message that seems to be not displayed here.

I agree, but first wanted to accept the merge while considering options.

I now combined the two entries. Especially useful as the two entries would not be together in the list (due to alphabetic sorting).
image

Do you think we should use a different logo? I think the label studio one is actually quite nice for "annotation tools"

**Comment by potthast** [comment]
Thanks, looks good!

As a logo, closer to use would be some text document icon where text is highlighted?

**Comment by johanneskiesel** [comment]
Ah, we could use the WAT-SL logo ;) https://webis.de/research.html#wat-sl (I did not add WAT-SL to facilities as it is not a ready-to-use service (you have to set it up for each project), though I did add it to the FAQ)

However, we just used label-studio for audio annotation.  But yeah... I actually now like the idea of using (part of) the WAT-SL logo. I'll try it later. Do you prefer to keep the document in the logo? I could also imagine to have just the lines and the marker.

**Comment by potthast** [comment]
Splendid idea!

I'd predict the document icon is what makes this "understandable". Since we are a text-heavy reserach group, focusing on that makes sense, even if label studio supports other formats.

**Comment by johanneskiesel** [comment]
I think it is nice: https://webis.de/facilities.html#annotation-tools

**Comment by potthast** [comment]
The horizontal bar look just a tiny bit blurry, though, which might be zoom artefact? Not important, I guess.

**Pull request merged**
